In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text' : ['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output' : [1,1,0,0]})

In [3]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [4]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1,3))

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
# printing the vocabulary (unique words present in the corpus)

print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [7]:
len(cv.vocabulary_)

15

In [8]:
print(bow[0].toarray())    # 1st sentence
print(bow[1].toarray())    # 2nd sentence

# so we can see our output as a vector below

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]]


In [9]:
# take a new sentence and predict for it :-

cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1]])

<h3> By changing one of the parameters in the sklearn library, we can decide what combinations of ngrams do we need to use: </h3>

(1,1) -> unigrams only

(2,2) -> bigrams only

(3,3) -> trigrams only

(1,2) -> unigrams and bigrams

(1,3) -> unigrams, bigrams, trigrams

(2,3) -> bigrams, trigrams and so on.